CREATE DATABASE OLIVETSISTEMAS;
USE OLIVETSISTEMAS;

CREATE TABLE USUARIO(
CODUSUARIO INT PRIMARY KEY,
EMAIL VARCHAR(100) UNIQUE,
SENHA VARCHAR(50) NOT NULL,
ATIVO CHAR(1) NOT NULL
)

INSERT INTO usuario (`CODUSUARIO`, `EMAIL`, `SENHA`,`ATIVO`) 
	VALUES (1, 'admin', 'admin','S');

